services:
  app:
    container_name: shakku-websocket-chat-app
    build: .
    tty: true
    volumes:
      - ${PWD}:/app
    ports:
      - 8080:8080
    environment:
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_USERNAME: ${DB_USERNAME}
      DB_USERPASS: ${DB_USERPASS}
      DB_DATABASENAME: ${DB_DATABASENAME}
      DB_PORT: ${DB_PORT}
      SESSION_KEY: ${SESSION_KEY}
      SERVERPORT: ${SERVERPORT}
    depends_on:
      - "db"
    restart: always
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASENAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_USERPASS}
      TZ: Asia/Tokyo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    tty: true
    restart: always

volumes:
  postgres-data:
    driver: local
