// Code generated by MockGen. DO NOT EDIT.
// Source: participating_room_repository.go
//
// Generated by this command:
//
//	mockgen -source=participating_room_repository.go -destination=../mock/repository/participating_room_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/Shakkuuu/websocket-chat-go-clean/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockParticipatingRoomRepo is a mock of ParticipatingRoomRepo interface.
type MockParticipatingRoomRepo struct {
	ctrl     *gomock.Controller
	recorder *MockParticipatingRoomRepoMockRecorder
}

// MockParticipatingRoomRepoMockRecorder is the mock recorder for MockParticipatingRoomRepo.
type MockParticipatingRoomRepoMockRecorder struct {
	mock *MockParticipatingRoomRepo
}

// NewMockParticipatingRoomRepo creates a new mock instance.
func NewMockParticipatingRoomRepo(ctrl *gomock.Controller) *MockParticipatingRoomRepo {
	mock := &MockParticipatingRoomRepo{ctrl: ctrl}
	mock.recorder = &MockParticipatingRoomRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipatingRoomRepo) EXPECT() *MockParticipatingRoomRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParticipatingRoomRepo) Create(ctx context.Context, participatingRoom *domain.ParticipatingRoom) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, participatingRoom)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockParticipatingRoomRepoMockRecorder) Create(ctx, participatingRoom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).Create), ctx, participatingRoom)
}

// DeleteByRoomID mocks base method.
func (m *MockParticipatingRoomRepo) DeleteByRoomID(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRoomID", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRoomID indicates an expected call of DeleteByRoomID.
func (mr *MockParticipatingRoomRepoMockRecorder) DeleteByRoomID(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRoomID", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).DeleteByRoomID), ctx, roomID)
}

// DeleteByUserID mocks base method.
func (m *MockParticipatingRoomRepo) DeleteByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockParticipatingRoomRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).DeleteByUserID), ctx, userID)
}

// DeleteByUserIDAndRoomID mocks base method.
func (m *MockParticipatingRoomRepo) DeleteByUserIDAndRoomID(ctx context.Context, userID, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDAndRoomID indicates an expected call of DeleteByUserIDAndRoomID.
func (mr *MockParticipatingRoomRepoMockRecorder) DeleteByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndRoomID", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).DeleteByUserIDAndRoomID), ctx, userID, roomID)
}

// GetAll mocks base method.
func (m *MockParticipatingRoomRepo) GetAll(ctx context.Context) (*domain.ParticipatingRooms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(*domain.ParticipatingRooms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockParticipatingRoomRepoMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).GetAll), ctx)
}

// GetByRoomID mocks base method.
func (m *MockParticipatingRoomRepo) GetByRoomID(ctx context.Context, roomID string) (*domain.ParticipatingRooms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoomID", ctx, roomID)
	ret0, _ := ret[0].(*domain.ParticipatingRooms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoomID indicates an expected call of GetByRoomID.
func (mr *MockParticipatingRoomRepoMockRecorder) GetByRoomID(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoomID", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).GetByRoomID), ctx, roomID)
}

// GetByUserID mocks base method.
func (m *MockParticipatingRoomRepo) GetByUserID(ctx context.Context, userID string) (*domain.ParticipatingRooms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.ParticipatingRooms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockParticipatingRoomRepoMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).GetByUserID), ctx, userID)
}

// GetByUserIDAndRoomID mocks base method.
func (m *MockParticipatingRoomRepo) GetByUserIDAndRoomID(ctx context.Context, userID, roomID string) (*domain.ParticipatingRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(*domain.ParticipatingRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDAndRoomID indicates an expected call of GetByUserIDAndRoomID.
func (mr *MockParticipatingRoomRepoMockRecorder) GetByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndRoomID", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).GetByUserIDAndRoomID), ctx, userID, roomID)
}

// GetUsersByRoomID mocks base method.
func (m *MockParticipatingRoomRepo) GetUsersByRoomID(ctx context.Context, roomID string) (*domain.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByRoomID", ctx, roomID)
	ret0, _ := ret[0].(*domain.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByRoomID indicates an expected call of GetUsersByRoomID.
func (mr *MockParticipatingRoomRepoMockRecorder) GetUsersByRoomID(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByRoomID", reflect.TypeOf((*MockParticipatingRoomRepo)(nil).GetUsersByRoomID), ctx, roomID)
}
